RoyalModelz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_store.urls')),
    path('verification/', include('verify_email.urls')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_store/urls.py
from django.urls import path

from .views import *
app_name = 'store'

urlpatterns = [

    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),

    path('', Home.as_view(), name='home'),
    path('product-detail/<product_id>/', ProductDetailView.as_view(), name='product'),

    path('admin-home/', AdminHome.as_view(), name='s_home'),
    path('staff/', AdminStaff.as_view(), name='s_staff'),
    path('staff-detail/<uid>/', StaffDetailView.as_view(), name='staff_detail'),
    path('staff-activities/<uid>/', StaffActivities.as_view(), name='staff_activities'),
    path('delete-staff/<uid>/', DeleteStaff.as_view(), name='delete_staff'),

    path('a-product-detail/<product_id>/', AdminProductDetailView.as_view(), name='staff_product_detail'),
    path('add-user/', AuthorRegistration.as_view(), name='add_staff'),
    path('admin-product-images/', AdminProductImages.as_view(), name='product_images'),

    path('add-product', AddProduct.as_view(), name='add_product'),
    path('delete-product/<product_id>/', DeleteProduct.as_view(), name='delete_product'),

    path('add-product-image', AddProductImage.as_view(), name='add_product_img'),
    path('delete-product-image/<pk>/', DeleteProductImage.as_view(), name='delete_product_img'),

    path('add-product-image', AddProductImage.as_view(), name='add_product_img'),
    path('update-product-image/<pk>/', UpdateProductImage.as_view(), name='update_product_img'),
    path('delete-product-image/<pk>/', DeleteProductImage.as_view(), name='delete_product_img'),

    path('add-product-category', AddProductCat.as_view(), name='add_product_cat'),
    path('update-product-category/<pk>/', UpdateProductCat.as_view(), name='update_product_cats'),
    path('delete-product-cat/<pk>/', DeleteProductCat.as_view(), name='delete_product_cat'),

    path('add-slide/', AddSlide.as_view(), name='add_slide'),
    path('update-slide/<pk>/', UpdateSlide.as_view(), name='update_slide'),
    path('delete-slide/<pk>/', DeleteSlide.as_view(), name='delete_slide'),

    path('update-first-name/<pk>/', FirstnameUpdate.as_view(), name='update_first_name'),
    path('update-surname/<pk>/', SurnameUpdate.as_view(), name='update_surname'),
    path('update-product-name/<product_id>/', ProductNameUpdate.as_view(), name='update_product_name'),
    path('update-product-product-category/<product_id>/', ProductCategoryUpdate.as_view(), name='update_product_cat'),
    path('update-product-brand/<product_id>/', ProductBrandUpdate.as_view(), name='update_product_brand'),
    path('update-product-color/<product_id>/', ProductColorsUpdate.as_view(), name='update_product_colors'),
    path('update-product-sizes/<product_id>/', ProductSizesUpdate.as_view(), name='update_product_sizes'),
    path('update-product-price/<product_id>/', ProductPriceUpdate.as_view(), name='update_product_price'),
    path('update-product-discount-price/<product_id>/', ProductDiscountPriceUpdate.as_view(),
         name='update_product_discount_price'),
    path('update-product-price-description/<product_id>/',
         ProductDescriptionUpdate.as_view(), name='update_product_description'),
    path('update-product-image-change/<pk>/', ProductProductImageUpdate.as_view(),
         name='update_product_image'),
    path('<pid>/order-product/', order_product, name='order_product'),
    path('update-product-order-status/<pk>/', ProductOrderStatusUpdate.as_view(), name='update_product_order_status'),
    path('orders/', AdminOrders.as_view(), name='admin_orders'),
]

main_store/views.py
from random import randint
from time import timezone

from django.core.paginator import Paginator
from django.http import JsonResponse, FileResponse, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.detail import BaseDetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from itertools import chain
from django.core.mail import send_mail

from .forms import *
from .models import *
from django.db.models import Count
from django.db.models import Q

# Create your views here.


def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username,
                            password=password)
        print(user)

        if user is not None:
            login(request, user)
            staff = Author.objects.get(user=request.user)
            act = Activity(actor=staff, action='Login')
            act.save()
            return redirect('store:s_home')

        else:
            messages.info(request, 'username or password is incorrect')

    return render(request, 'forms/login.html')


def logoutUser(request):
    staff = Author.objects.get(user=request.user)
    act = Activity(actor=staff, action='Logout')
    act.save()
    logout(request)
    return redirect('store:login')


class Home(View):

    def get(self, *args, **kwargs):
        products = Product.objects.all()
        slides = Slide.objects.all()
        product_cats = ProductCategory.objects.all()
        product_images = ProductImage.objects.filter(lead=True)

        context = {
            'products': products,
            'slides': slides,
            'product_cats': product_cats,
            'product_images': product_images,
        }
        print([x.product for x in product_images])

        return render(self.request, 'home.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_details.html'
    slug_field = 'product_id'
    slug_url_kwarg = 'product_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all().exclude(product_id=self.object.product_id)
        product_images = ProductImage.objects.filter(product=self.object)
        product_images_o = ProductImage.objects.filter(lead=True).exclude(product=self.object)
        product_cats = ProductCategory.objects.all()

        context["products"] = products
        context["product_images"] = product_images
        context["product_images_o"] = product_images_o
        context["product_cats"] = product_cats

        return context


# --------------------------------------Admin section-----------------------


class AdminHome(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        products = Product.objects.all()
        product_cats = ProductCategory.objects.all()
        slides = Slide.objects.all()
        staff = Author.objects.all()
        product_images = ProductImage.objects.filter(lead=True)
        orders = ProductOrder.objects.filter(complete=False)[:9]

        context = {
            'products': products,
            'product_cats': product_cats,
            'slides': slides,
            'staff': staff,
            'product_images': product_images,
            'orders': orders,
        }

        return render(self.request, 'staff/home.html', context)


class AdminStaff(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        staff = Author.objects.all()

        context = {
            'staff': staff,
        }

        return render(self.request, 'staff/staff.html', context)


class StaffDetailView(LoginRequiredMixin, DetailView):
    model = Author
    template_name = 'staff/staff-profile.html'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        actor = Author.objects.get(user=self.object.user)
        acts = Activity.objects.filter(actor=self.object).order_by('-action_date')[:10]
        context["acts"] = acts
        return context


class StaffActivities(LoginRequiredMixin, DetailView):
    model = Author
    template_name = 'staff/staff-activities.html'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    # paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        acts = Activity.objects.filter(actor=self.object).order_by('-action_date')
        paginator = Paginator(acts, 10)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context["acts"] = page_obj
        return context


class AdminProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'staff/product_detail.html'
    slug_field = 'product_id'
    slug_url_kwarg = 'product_id'



class AdminProductImages(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        products = Product.objects.all()
        product_cats = ProductCategory.objects.all()
        product_images = ProductImage.objects.all()

        context = {
            'products': products,
            'product_cats': product_cats,
            'product_images': product_images,
        }
        print([x.product for x in product_images])

        return render(self.request, 'staff/product_images.html', context)


def random_int():
    random_ref = randint(0, 9999999999)
    uid = random_ref
    return uid


class AuthorRegistration(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('users.add_user', 'users.add_student')

    def get(self, request):
        form = CreateUserForm()
        profile_form = AuthorProfileForm()

        context = {
            'form': form,
            'profile_form': profile_form,
        }
        return render(request, 'forms/registration.html', context)

    def post(self, request, *args, **kwargs):
        u_name = request.POST.get('username')
        # print(request.POST ,'', request.FILES)
        profile_form = AuthorProfileForm(request.POST, request.FILES)
        form = CreateUserForm(request.POST)

        if profile_form.is_valid() and form.is_valid():
            user = form.save()
            username = user.username

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.uid = random_int()
            profile.save()
            staff = Author.objects.get(user=request.user)
            act = Activity(actor=staff, type='Add', action=f'Account created for {username}')
            act.save()

            messages.success(request, 'Account was created for ' + username)

            return redirect('store:s-home')

        else:
            # when the form has an error
            print(profile_form.errors)
            profile_form = AuthorProfileForm()
            messages.success(request, 'Fill out all the necessary details ')
            context = {
                'form': form,
                'profile_form': profile_form,
            }
            return render(request, 'forms/registration.html', context)


class DeleteStaff(LoginRequiredMixin, DeleteView):

    model = Author
    template_name = 'forms/delete_staff.html'
    success_url = reverse_lazy('store:s_home')


class AddProduct(LoginRequiredMixin, CreateView):

    model = Product
    form_class = ProductForm
    template_name = 'forms/product.html'
    success_url = reverse_lazy('store:s_home')

    def form_valid(self, form, *args, **kwargs):
        # print(self.request.POST)
        author = Author.objects.get(user=self.request.user)
        form = form.save(commit=False)
        form.product_id = random_int()
        form.author = author

        form.save()

        staff = Author.objects.get(user=self.request.user)
        act = Activity(actor=staff, type='Add', action=f'Product added: {form.name}')
        act.save()
        # messages.success(self.request, 'Post was successfully added')
        # return redirect('store:s_home')
        product = Product.objects.get(product_id=form.product_id)

        return HttpResponseRedirect(reverse('store:staff_product_detail', kwargs={'product_id': product.product_id}))

    def form_invalid(self, form, *args, **kwargs):
        # print(self.request.POST)
        print(form.errors)
        # messages.success(self.request, 'Post was not added, ensure that you filled the form correctly')
        return render(self.request, 'forms/product.html', {'form': form})


class DeleteProduct(LoginRequiredMixin, DeleteView):

    model = Product
    template_name = 'forms/delete_product.html'
    slug_field = 'product_id'
    slug_url_kwarg = 'product_id'
    success_url = reverse_lazy('store:s_home')


class AddProductImage(LoginRequiredMixin, CreateView):

    model = ProductImage
    form_class = ProductImageForm
    template_name = 'forms/product-image.html'

    def form_valid(self, form, *args, **kwargs):
        # print(self.request.POST)
        form = form.save(commit=False)
        staff = Author.objects.get(user=self.request.user)
        act = Activity(actor=staff, type='Add', action=f'Product Image category added: {form.product}')
        act.save()
        if form.lead:
            print(self.object,':',form.product)
            try:
                old_lead = ProductImage.objects.get(product=form.product, lead=True)

main_store/templates/css.html
 {% load static %}
{% block css %}


 <!-- normalize core CSS -->
<!--    <link href="{% static 'css/normalize.css' %}" rel="stylesheet">-->
    <link rel="shortcut icon" href="{% static 'assets/images/fav.png' %}" type="image">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fontawesome-free-6.1.1-web/css/all.css' %}">
 {% endblock %}

main_store/templates/footer.html
<!-- FOOTER 1 -->
{% load static %}

<footer id="hm__footer">
            <section id="hm__footer__top">
                <header id="hm__footer__top__address">
                    <div class="hm__footer__top__address__icon"><i class="fas fa-map-marker-alt" style="color: rgb(18, 119, 3);"></i></div>
                    <div class="hm__footer__top__address__txt">
                        Lugbe Federal Housing
                        <br/> Opposite Siamatrix Event Center, Abuja.
                    </div>
                </header>
                <div id="hm__footer__top__cont__info__div">
                    <header id="hm__footer__cont__info__head">
                        Contact us
                    </header>
                    <section id="hm__footer__cont__info__dit">
                        <div class="hm__footer__top__cont__info">
                            <i class="fas fa-envelope" style="color: rgb(37, 36, 0);"></i>
                            <div class="hm__footer__top__cont__info__txt"><a href="mailto:oluchiechukwuka@gmail.com">royalmodelz mail</a></div>
                        </div>
                        <div class="hm__footer__top__cont__info">
                            <i class="fas fa-phone" style="color: rgb(202, 181, 128);"></i>
                            <div class="hm__footer__top__cont__info__txt"><a href="tel:+234 809 349 0689">+234 809 349 0689</a></div>
                        </div>
                    </section>
                </div>
                <div id="hm__footer__top__socials__div">
                    <a class="hm__footer__top__socials__item" href="https://m.facebook.com/100054371206664/" style="color: blue;"><i class="fab fa-facebook-square" aria-hidden="true"></i></a>
<!--                    <a class="hm__footer__top__socials__item" href="" style="color: rgb(7, 242, 234);">-->
<!--                        <i class="fab fa-twitter" aria-hidden="true"></i>-->
<!--                    </a>-->
<!--                    <a class="hm__footer__top__socials__item" href="" style="color: rgb(244, 8, 8);">-->
<!--                        <i class="fab fa-youtube" aria-hidden="true"></i>-->
<!--                    </a>-->
                    <a class="hm__footer__top__socials__item" href="https://www.instagram.com/royalmodelz_/" style="color: rgb(255, 106, 0);"><i class="fab fa-instagram" aria-hidden="true"></i></a>
                </div>
            </section>
            <section id="hm__footer__low">
                <span>© 2022 <span class="footer-brand">Royal</span> Modelz. All righrs reserved</span>
                <i>Design by <a href="">leoklems</a></i>
            </section>

        </footer>

main_store/templates/home.html
{% extends 'main_store.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <main id="hm_main">
        <header id="hm_top_h">
            {% include 'navigation.html' %}
            {% if slides %}
            <article id="hm__slides">
                <div class="hm_slides_container">
                    {%for s in slides%}
                        {%if s.link%}
                            <a href="{{s.link}}" id="hm_slide" class="mySlides fade">
                                <section id="hm_slide_img" class="hm_slide_sec"><img src="{{s.image.url}}" alt="" id="hm__top__ad__img"></section>
                            </a>
                        {%else%}
                            <div id="hm_slide" class="mySlides fade">
                                <section id="hm_slide_img" class="hm_slide_sec"><img src="{{s.image.url}}" alt="" id="hm__top__ad__img"></section>
                            </div>
                        {%endif%}
                    {%endfor%}
<!--                    {% if slides.count > 1 %}-->
<!--                    <div class="hm__body__prev__next__slide">-->
<!--                        <a class="prev" onclick="plusSlides(-1)">&#10094</a>-->
<!--                        <a class="next" onclick="plusSlides(1)">&#10095</a>-->
<!--                    </div>-->
<!--                    {%else%}-->
<!--                    {%endif%}-->
                </div>
            </article>
            {%else%}
            {%endif%}
        </header>
        <article id="hm_main_body">
            {% if products %}
                {%for p_cat in product_cats%}
                {% if p_cat.product_categories.count > 0 %}
                <section class="hm_main_body_sec" id="hm_b_{{p_cat.name}}">
                <header class="hm_main_body_sec_head">{{p_cat.name}}</header>
                <div class="hm_main_body_sec_body">
                    {%for p in products %}
                    {% if p.category == p_cat %}

                    <a href="{% url 'store:product' p.product_id %}" class="hm_main_body_art">
                        <header class="hm_main_body_art_head">{{p.name}}</header>
                            {%for img in product_images %}
                            {% if img.product.name == p.name %}
                                <img src="{{img.file.url}}" alt="Article image" class="hm_main_body_art_img">
                            {%else%}
                            {%endif%}
                            {%endfor%}
                        <footer class="hm_main_body_art_footer">
<!--                            <section class="badge __new">new</section>-->
                            {% if p.discount_price %}
                            <section class="price">&#8358; {{p.discount_price}} <span class="disc_badge">-{{p.percentage_discount}}%</span></section>
                            {%else%}
                            <section class="price">&#8358; {{p.price}} </section>
                            {%endif%}

                        </footer>
                    </a>
                    {%else%}
                    {%endif%}
                    {%endfor%}
                </div>
                </section>
                {%else%}
                {%endif%}
                {%endfor%}
            {%else%}
            {%endif%}
        </article>
        {% include 'footer.html' %}
        {% include 'whatsapp.html' %}

    </main>
{% endblock %}

main_store/templates/js.html
{% load static %}
{% block js%}
    <script src="{% static 'assets/js/jquery.js'%}"></script>
    <script src="{% static 'assets/js/main.js'%}"></script>
  {% endblock  %}

main_store/templates/main_store.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%include 'meta.html'%}
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    {%include 'css.html'%}

</head>
<body>
    {% block content %}

    {% endblock %}
    {%include 'js.html'%}
</body>
</html>

main_store/templates/meta.html
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

main_store/templates/navigation.html
{% load static %}
{% load cache %}

<article id="hm_menu_bar">
                <a href="{% url 'store:home' %}" id="hm__site__logo">
                    <img src="{% static 'assets/images/logo.png'%}" alt="site logo" id="hm__img__logo">
                </a>
                <a id="hm__header__dail" href="tel:+234 809 349 0689"><i class="fas fa-phone"></i> call us 24/7</a>
                <nav id="hm__nav" class="hm__nav">
                    <ul id="hm__nav__list">
                        <li class="hm__nav__list__item">
                            <a href="{% url 'store:home' %}" class="hm__nav__item__link">home</a>
                        </li>
                        <li class="hm__nav__list__item">
                            <a href="" id="hm_nav_cat_outs" class="hm__nav__item__link">Categories <i class="fas fa-caret-down"></i></a>
                            {% if product_cats %}
                            <ul id="hm_nav_cat_items" class="hm_nav_cat">
                                {% for cat in product_cats%}
                                <li class="hm_nav_cat_item">
                                    <a href="#hm_b_{{cat.name}}" id="hm_nav_cat_item_link" class="hm_nav_cat_item_link">{{cat.name}}</a>
                                </li>
                                {%endfor%}
                            </ul>
                            {%else%}
                            {%endif%}

                        </li>
                        <li class="hm__nav__list__item">
                            <a href="#hm__footer__top__cont__info__div" class="hm__nav__item__link" id="hm__nav__contact_us">contact us</a>
                        </li>
                        <!-- <li class="hm__nav__list__item">
                            <a href="#hm__about__us" class="hm__nav__item__link" id="hm__nav__aboutus">about us</a>
                        </li> -->
                        <!-- <li id="hm__nav__list__item">
                            <a href="" id="hm__nav__item__link">policy</a>
                        </li> -->
                    </ul>
                </nav>
                <a href="" id="hm__menu__btn" class="hm__menu__btn"><i class="fas fa-bars"></i></a>
            </article>

main_store/templates/navigation2.html
{% load static %}
{% load cache %}

<article id="hm_menu_bar">
                <a href="{% url 'store:home' %}" id="hm__site__logo">
                    <img src="{% static 'assets/images/logo.png'%}" alt="site logo" id="hm__img__logo">
                </a>
                <a id="hm__header__dail" href="tel:+234 809 349 0689"><i class="fas fa-phone"></i> call us 24/7</a>
                <nav id="hm__nav" class="hm__nav">
                    <ul id="hm__nav__list">
                        <li class="hm__nav__list__item">
                            <a href="{% url 'store:home' %}" class="hm__nav__item__link">home</a>
                        </li>
                    </ul>
                </nav>
                <a href="" id="hm__menu__btn" class="hm__menu__btn"><i class="fas fa-bars"></i></a>
            </article>

main_store/templates/order_product.html
{% extends 'staff/main.html' %}
{% load static %}
{% block title %}Order{% endblock %}

{% block content %}
    <main id="all__forms" class="front_form">

        <section id="forms__sec" class="mini_forms__sec order_form">
            <article id="form__login">
                <header>Please provide at least one of these information so we can contact you.</header>
                <form method="post" id="login">
                        {% csrf_token %}
                        <input type="email" name="email" id="form__login__email" placeholder="your email">
                        <input type="tel" name="phone_number" id="form__login__pwrd" placeholder="phone number">


                        <div id="form_ctrl_btns_add" class="form_ctrl_btns">
                            <a href="{% url 'store:product' product.product_id%}" class="form_ctrl_btn_back">Cancle</a>
                            <input type="submit" value="Order" id="form__login__submit">
                        </div>
                    </form>
            </article>
        </section>
    </main>
{% endblock %}

main_store/templates/product_details.html
{% extends 'main_store.html' %}
{% load static %}
{% block title %}Product details{% endblock %}

{% block content %}
    <main id="hm_main">
        <header id="hm_top_h">
            {% include 'navigation2.html' %}
        </header>
        <article id="dit_body">
            <header id="dit_body_head">
                <div class="dit_body_head_items">
                    {% for img in product_images %}
                    <img src="{{img.file.url}}" alt="Article image" class="dit_body_img hm_main_body_art_img">
                    {%endfor%}
                </div>
            </header>
            <a href="{% url 'store:order_product' object.product_id%}" class="order_btn">Order</a>
            <section id="dit_body_dit">
                <header class="dit_body_dit_name">{{object.category}}
<!--                    <span class="badge">new</span>-->
                </header>
                <div class="dit_body_dit_brand">
                    <span class="dit_body_brand_cap _cap">brand: </span>
                    <span class="dit_body_brand_name">{{object.category}}</span>
                </div>
                <div class="dit_body_dit_size">
                    <span class="dit_body_size_cap _cap">sizes available</span>
                    <span class="dit_body_sizes">{{object.sizes}}</span>
                </div>
                <div class="dit_body_dit_color">
                    <span class="dit_body_color_cap _cap">colors available: </span>
                    <span class="dit_body_colors">{{object.colors}}</span>
                </div>
                <div class="dit_body_dit_price">
                    {% if object.discount_price %}
                    <span class="dit_body_disc_price">&#8358; {{object.discount_price}}</span>
                    <del class="dit_body_norm_price">&#8358; {{object.price}}</del>
                    <span class="disc_badge">-{{object.percentage_discount}}%</span>
                    {%else%}
                    <span class="dit_body_disc_price">&#8358; {{object.price}}</span>
                    {%endif%}
                </div>
                <div class="dit_body_dit_size">
                    <span class="dit_body_size_cap _cap">Description :</span>
                    <span class="dit_body_desc">{{object.description}}</span>
                </div>
            </section>
        </article>
        <article id="hm_main_body">
            {% if products %}
                <section class="hm_main_body_sec" id="hm_b_suits">
                <div class="hm_main_body_sec_body">
                    {%for p in products %}
                    <a href="{% url 'store:product' p.product_id%}" class="hm_main_body_art">
                        <header class="hm_main_body_art_head">{{p.name}}</header>
                            {%for img in product_images_o %}
                            {% if img.product.name == p.name %}
                                <img src="{{img.file.url}}" alt="Article image" class="hm_main_body_art_img">
                            {%else%}
                            {%endif%}
                            {%endfor%}
                        <footer class="hm_main_body_art_footer">
<!--                            <section class="badge __new">new</section>-->
                            {% if p.discount_price %}
                            <section class="price">&#8358; {{p.discount_price}} <span class="disc_badge">-{{p.percentage_discount}}%</span></section>
                            {%else%}
                            <section class="price">&#8358; {{p.price}} </section>
                            {%endif%}

                        </footer>
                    </a>
                    {%endfor%}
                </div>
                </section>
            {%else%}
            {%endif%}
        </article>
        {% include 'footer.html' %}
        {% include 'whatsapp.html' %}

    </main>
{% endblock %}

main_store/templates/whatsapp.html
{% load static %}

<div id="always__on">
            <span class=""><a href="https://wa.me/+234 809 349 0689"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></span>
        </div>