RoyalModelz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_store.urls')),
    path('verification/', include('verify_email.urls')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_store/urls.py
from django.urls import path

from .views import *
app_name = 'store'

urlpatterns = [

    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),

    path('', Home.as_view(), name='home'),
    path('product-detail/<product_id>/', ProductDetailView.as_view(), name='product'),

    path('admin-home/', AdminHome.as_view(), name='s_home'),
    path('staff/', AdminStaff.as_view(), name='s_staff'),
    path('staff-detail/<uid>/', StaffDetailView.as_view(), name='staff_detail'),
    path('staff-activities/<uid>/', StaffActivities.as_view(), name='staff_activities'),
    path('delete-staff/<uid>/', DeleteStaff.as_view(), name='delete_staff'),

    path('a-product-detail/<product_id>/', AdminProductDetailView.as_view(), name='staff_product_detail'),
    path('add-user/', AuthorRegistration.as_view(), name='add_staff'),
    path('admin-product-images/', AdminProductImages.as_view(), name='product_images'),

    path('add-product', AddProduct.as_view(), name='add_product'),
    path('delete-product/<product_id>/', DeleteProduct.as_view(), name='delete_product'),

    path('add-product-image', AddProductImage.as_view(), name='add_product_img'),
    path('delete-product-image/<pk>/', DeleteProductImage.as_view(), name='delete_product_img'),

    path('add-product-image', AddProductImage.as_view(), name='add_product_img'),
    path('update-product-image/<pk>/', UpdateProductImage.as_view(), name='update_product_img'),
    path('delete-product-image/<pk>/', DeleteProductImage.as_view(), name='delete_product_img'),

    path('add-product-category', AddProductCat.as_view(), name='add_product_cat'),
    path('update-product-category/<pk>/', UpdateProductCat.as_view(), name='update_product_cats'),
    path('delete-product-cat/<pk>/', DeleteProductCat.as_view(), name='delete_product_cat'),

    path('add-slide/', AddSlide.as_view(), name='add_slide'),
    path('update-slide/<pk>/', UpdateSlide.as_view(), name='update_slide'),
    path('delete-slide/<pk>/', DeleteSlide.as_view(), name='delete_slide'),

    path('update-first-name/<pk>/', FirstnameUpdate.as_view(), name='update_first_name'),
    path('update-surname/<pk>/', SurnameUpdate.as_view(), name='update_surname'),
    path('update-product-name/<product_id>/', ProductNameUpdate.as_view(), name='update_product_name'),
    path('update-product-product-category/<product_id>/', ProductCategoryUpdate.as_view(), name='update_product_cat'),
    path('update-product-brand/<product_id>/', ProductBrandUpdate.as_view(), name='update_product_brand'),
    path('update-product-color/<product_id>/', ProductColorsUpdate.as_view(), name='update_product_colors'),
    path('update-product-sizes/<product_id>/', ProductSizesUpdate.as_view(), name='update_product_sizes'),
    path('update-product-price/<product_id>/', ProductPriceUpdate.as_view(), name='update_product_price'),
    path('update-product-discount-price/<product_id>/', ProductDiscountPriceUpdate.as_view(),
         name='update_product_discount_price'),
    path('update-product-price-description/<product_id>/',
         ProductDescriptionUpdate.as_view(), name='update_product_description'),
    path('update-product-image-change/<pk>/', ProductProductImageUpdate.as_view(),
         name='update_product_image'),
    path('<pid>/order-product/', order_product, name='order_product'),
    path('update-product-order-status/<pk>/', ProductOrderStatusUpdate.as_view(), name='update_product_order_status'),
    path('orders/', AdminOrders.as_view(), name='admin_orders'),
]

main_store/views.py
from random import randint
from time import timezone

from django.core.paginator import Paginator
from django.http import JsonResponse, FileResponse, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.detail import BaseDetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from itertools import chain
from django.core.mail import send_mail

from .forms import *
from .models import *
from django.db.models import Count
from django.db.models import Q

# Create your views here.


def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username,
                            password=password)
        print(user)

        if user is not None:
            login(request, user)
            staff = Author.objects.get(user=request.user)
            act = Activity(actor=staff, action='Login')
            act.save()
            return redirect('store:s_home')

        else:
            messages.info(request, 'username or password is incorrect')

    return render(request, 'forms/login.html')


def logoutUser(request):
    staff = Author.objects.get(user=request.user)
    act = Activity(actor=staff, action='Logout')
    act.save()
    logout(request)
    return redirect('store:login')


class Home(View):

    def get(self, *args, **kwargs):
        products = Product.objects.all()
        slides = Slide.objects.all()
        product_cats = ProductCategory.objects.all()
        product_images = ProductImage.objects.filter(lead=True)

        context = {
            'products': products,
            'slides': slides,
            'product_cats': product_cats,
            'product_images': product_images,
        }
        print([x.product for x in product_images])

        return render(self.request, 'home.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_details.html'
    slug_field = 'product_id'
    slug_url_kwarg = 'product_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all().exclude(product_id=self.object.product_id)
        product_images = ProductImage.objects.filter(product=self.object)
        product_images_o = ProductImage.objects.filter(lead=True).exclude(product=self.object)
        product_cats = ProductCategory.objects.all()

        context["products"] = products
        context["product_images"] = product_images
        context["product_images_o"] = product_images_o
        context["product_cats"] = product_cats

        return context


# --------------------------------------Admin section-----------------------


class AdminHome(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        products = Product.objects.all()
        product_cats = ProductCategory.objects.all()
        slides = Slide.objects.all()
        staff = Author.objects.all()
        product_images = ProductImage.objects.filter(lead=True)
        orders = ProductOrder.objects.filter(complete=False)[:9]

        context = {
            'products': products,
            'product_cats': product_cats,
            'slides': slides,
            'staff': staff,
            'product_images': product_images,
            'orders': orders,
        }

        return render(self.request, 'staff/home.html', context)


class AdminStaff(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        staff = Author.objects.all()

        context = {
            'staff': staff,
        }

        return render(self.request, 'staff/staff.html', context)


class StaffDetailView(LoginRequiredMixin, DetailView):
    model = Author
    template_name = 'staff/staff-profile.html'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        actor = Author.objects.get(user=self.object.user)
        acts = Activity.objects.filter(actor=self.object).order_by('-action_date')[:10]
        context["acts"] = acts
        return context


class StaffActivities(LoginRequiredMixin, DetailView):
    model = Author
    template_name = 'staff/staff-activities.html'
    slug_field = 'uid'
    slug_url_kwarg = 'uid'

    # paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        acts = Activity.objects.filter(actor=self.object).order_by('-action_date')
        paginator = Paginator(acts, 10)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context["acts"] = page_obj
        return context


class AdminProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'staff/product_detail.html'
    slug_field = 'product_id'
    slug_url_kwarg = 'product_id'



class AdminProductImages(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        products = Product.objects.all()
        product_cats = ProductCategory.objects.all()
        product_images = ProductImage.objects.all()

        context = {
            'products': products,
            'product_cats': product_cats,
            'product_images': product_images,
        }
        print([x.product for x in product_images])

        return render(self.request, 'staff/product_images.html', context)


def random_int():
    random_ref = randint(0, 9999999999)
    uid = random_ref
    return uid


class AuthorRegistration(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = ('users.add_user', 'users.add_student')

    def get(self, request):
        form = CreateUserForm()
        profile_form = AuthorProfileForm()

        context = {
            'form': form,
            'profile_form': profile_form,
        }
        return render(request, 'forms/registration.html', context)

    def post(self, request, *args, **kwargs):
        u_name = request.POST.get('username')
        # print(request.POST ,'', request.FILES)
        profile_form = AuthorProfileForm(request.POST, request.FILES)
        form = CreateUserForm(request.POST)

        if profile_form.is_valid() and form.is_valid():
            user = form.save()
            username = user.username

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.uid = random_int()
            profile.save()
            staff = Author.objects.get(user=request.user)
            act = Activity(actor=staff, type='Add', action=f'Account created for {username}')
            act.save()

            messages.success(request, 'Account was created for ' + username)

            return redirect('store:s-home')

        else:
            # when the form has an error
            print(profile_form.errors)
            profile_form = AuthorProfileForm()
            messages.success(request, 'Fill out all the necessary details ')
            context = {
                'form': form,
                'profile_form': profile_form,
            }
            return render(request, 'forms/registration.html', context)


class DeleteStaff(LoginRequiredMixin, DeleteView):

    model = Author
    template_name = 'forms/delete_staff.html'
    success_url = reverse_lazy('store:s_home')


class AddProduct(LoginRequiredMixin, CreateView):

    model = Product
    form_class = ProductForm
    template_name = 'forms/product.html'
    success_url = reverse_lazy('store:s_home')

    def form_valid(self, form, *args, **kwargs):
        # print(self.request.POST)
        author = Author.objects.get(user=self.request.user)
        form = form.save(commit=False)
        form.product_id = random_int()
        form.author = author

        form.save()

        staff = Author.objects.get(user=self.request.user)
        act = Activity(actor=staff, type='Add', action=f'Product added: {form.name}')
        act.save()
        # messages.success(self.request, 'Post was successfully added')
        # return redirect('store:s_home')
        product = Product.objects.get(product_id=form.product_id)

        return HttpResponseRedirect(reverse('store:staff_product_detail', kwargs={'product_id': product.product_id}))

    def form_invalid(self, form, *args, **kwargs):
        # print(self.request.POST)
        print(form.errors)
        # messages.success(self.request, 'Post was not added, ensure that you filled the form correctly')
        return render(self.request, 'forms/product.html', {'form': form})


class DeleteProduct(LoginRequiredMixin, DeleteView):

    model = Product
    template_name = 'forms/delete_product.html'
    slug_field = 'product_id'
    slug_url_kwarg = 'product_id'
    success_url = reverse_lazy('store:s_home')


class AddProductImage(LoginRequiredMixin, CreateView):

    model = ProductImage
    form_class = ProductImageForm
    template_name = 'forms/product-image.html'

    def form_valid(self, form, *args, **kwargs):
        # print(self.request.POST)
        form = form.save(commit=False)
        staff = Author.objects.get(user=self.request.user)
        act = Activity(actor=staff, type='Add', action=f'Product Image category added: {form.product}')
        act.save()
        if form.lead:
            print(self.object,':',form.product)
            try:
                old_lead = ProductImage.objects.get(product=form.product, lead=True)

main_store/templates/staff/home.html
{% extends 'staff/main.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <main id="gall__main__main">
        {% include 'staff/header.html' %}
        {% include 'staff/navigation.html' %}
        <section id="gall__main" class="dit__pg">

            <article id="table__one">
                <table>
                    <caption><span class="gall_art_sec_name">Pending orders</span>
                    </caption>
                    {% if orders %}
                    <tbody id="table__one__body">
                        <tr>
<!--                            <th>s/n</th>-->
                            <th>phone</th>
                            <th>email</th>
                            <th>product</th>
                            <th>status</th>
                        </tr>
                        <tr>
                            {%for order in orders%}
<!--                            <td>{{forloop.counter}}</td>-->
                            <td>{{order.phone_number}}</td>
                            <td>{{order.email}}</td>
                            <td>{{order.product}}</td>
                            <td>
                                <div class="table__ctrl__btns">
                                    <a href="{% url 'store:update_product_order_status' order.id %}" class="tbl__btn__edit"><i class="far fa-check-circle"></i></a>
                                </div>
                            </td>
                            {%endfor%}

                        </tr>
                    </tbody>
                    {%else%}
                    {%endif%}
                </table>
            </article>

            <article class=" gall__art__one__main ">
                <header><span class="gall_art_sec_name">Slides</span>
                    <span class="gall_art_item_add_btn">
                        <a href="{% url 'store:add_slide' %}" class="add_item_btn"><i class="fas fa-plus "></i> slides</a>
                    </span>
                </header>
                {% if slides %}
                <section class="gall__arts " id="gall__art__one ">
                    {% for s in slides %}
                    <div class="gall__art__img__div ">
                        <img src="{{s.image.url}}" alt="photo image " class="gall__art__one__img ">
                        <div class="gall__art__one__img__desc ">
                             <a href="{% url 'store:update_slide' s.id %}" class="tbl__btn__edit"><i class="far fa-edit"></i><i class="fas fa-camera"></i></a>
                            {% if s.link %}
                            <a href="" class="tbl__btn__edit"><i class="far fa-edit"></i><i class="fas fa-anchor"></i></a>
                            {%else%}
                            {%endif%}
                            <a href="{% url 'store:delete_slide' s.id %}"  class="tbl__btn__delete "><i class="fas fa-trash"></i></a>
<!--                            <a href=" " class="gall__art__img__one__name ">yellow touch</a>-->
<!--                            <section class="gall__art__img__one__num "><a href=" " class="tbl__btn__delete ">-->
<!--                                <i class="fas fa-trash "></i></a>-->
<!--                            </section>-->
                        </div>
                    </div>
                    {%endfor%}
                </section>
                {%else%}
                {%endif%}
            </article>

            <article class=" gall__art__one__main ">
                {%for p_cat in product_cats%}
                <header><span class="gall_art_sec_name">{{p_cat.name}}</span>
                    <span class="gall_art_item_add_btn">
                        <a href="{% url 'store:add_product' %}" class="add_item_btn"><i class="fas fa-plus "></i> products</a>
                    </span>
                </header>
                {% if products %}

                {% if p_cat.product_categories.count > 0 %}
                <section class="gall__arts " id="gall__art__one ">
                    {%for p in products %}
                    {% if p.category == p_cat %}
                    <div class="gall__art__img__div ">
                        {%for img in product_images %}
                        {% if img.product.name == p.name %}
                        <img src="{{img.file.url}}" alt="photo image" class="gall__art__one__img hm_main_body_art_img">
                        {%else%}
                        {%endif%}
                        {%endfor%}
                        <div class="gall__art__one__img__desc">
                            <a href="{% url 'store:staff_product_detail' p.product_id %}" class="gall__art__img__one__name tbl__btn__view"><i class="far fa-eye"></i></a>
                            <section class="gall__art__img__one__num "><a href="{% url 'store:delete_product' p.product_id %} " class="tbl__btn__delete ">
                                <i class="fas fa-trash "></i></a>
                            </section>
                        </div>
                    </div>
                    {%else%}
                    {%endif%}
                    {%endfor%}
                </section>
                {%else%}
                {%endif%}

                {%else%}
                {%endif%}
                {%endfor%}
            </article>


            <article id="table__one">
                <table>
                    <caption><span class="gall_art_sec_name">categories</span>
                    <span class="gall_art_item_add_btn">
                        <a href="{% url 'store:add_product_cat' %}" class="add_item_btn"><i class="fas fa-plus "></i> product category</a>
                    </span></caption>
                    {% if product_cats %}
                    <tbody id="table__one__body">
                        <tr>
                            <th>s/n</th>
                            <th>name</th>
                            <th>number of products</th>
                            <th>controls</th>
                        </tr>
                        <tr>
                            {%for p_cat in product_cats%}
                            <td>{{forloop.counter}}</td>
                            <td>{{p_cat.name}}</td>
                            <td>{{p_cat.product_categories.count}}</td>
                            <td>
                                <div class="table__ctrl__btns">
                                    <a href="{% url 'store:update_product_cats' p_cat.id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'store:delete_product_cat' p_cat.id %}" class="tbl__btn__delete"><i class="fas fa-trash"></i></a>
                                </div>
                            </td>
                            {%endfor%}

                        </tr>
                    </tbody>
                    {%else%}
                    {%endif%}
                </table>
            </article>

        </section>
    </main>
{% endblock %}

main_store/templates/staff/js.html
{% load static %}
{% block js%}
    <script src="{% static 'assets/js/jquery.js'%}"></script>
    <script src="{% static 'assets/js/main_admin.js'%}"></script>
  {% endblock  %}

main_store/templates/staff/navigation.html
{% load static %}
{% load cache %}

<nav id="hm__sidebar" class="hm__sidebar">
    <header id="hm__user__info">
        <img src="{{request.user.author.profile_pic.url}}" alt="user display image" id="hm__dp">
        <section>
            <div id="hm__user__name">{{request.user.author.username}}</div>
            <div id="hm__user__title">admim</div>
        </section>
    </header>
    <section id="hm__nav">
        <ul>
            <li class="hm__nav__item">
                <a href="{% url 'store:s_home' %}" class="hm__nav__icon">
                    <span class="hm__nav__icon ">
                        <i class="fas fa-home"></i>
                    </span>
                    <span class="hm__nav__cont">Home</span>
                </a>
            </li>
            <li class="hm__nav__item ">
                <a href="{% url 'store:product_images' %}" class="hm__nav__link ">
                    <span class="hm__nav__icon ">
                        <i class="fas fa-camera "></i>
                    </span>
                    <span class="hm__nav__cont ">Product Images</span>
                </a>
            </li>
            <li class="hm__nav__item ">
                <a href="{% url 'store:admin_orders' %}" class="hm__nav__link ">
                    <span class="hm__nav__icon ">
                        <i class="fas fa-tasks "></i>
                    </span>
                    <span class="hm__nav__cont ">Orders</span>
                </a>
            </li>
            <li class="hm__nav__item ">
                <a href="{% url 'store:logout' %}" class="hm__nav__link ">
                    <span class="hm__nav__icon ">
                        <i class="fas fa-sign-out-alt "></i>
                    </span>
                    <span class="hm__nav__cont ">Logout</span>
                </a>
            </li>
<!--            <li class="hm__nav__item ">-->
<!--                <a href="{% url 'store:s_home' %}" class="hm__nav__link ">-->
<!--                    <span class="hm__nav__icon "><i class="fas fa-message "></i></span><span class="hm__nav__cont ">Chat</span>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="hm__nav__item">-->
<!--                <a href="{% url 'store:s_home' %}" class="hm__nav__link ">-->
<!--                    <span class="hm__nav__icon "><i class="fas fa-gear "></i></span><span class="hm__nav__cont ">setting</span>-->
<!--                </a>-->
<!--            </li>-->
        </ul>
    </section>
</nav>

main_store/templates/staff/product_detail.html
{% extends 'staff/main.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <main id="gall__main__main" class="dit__pg">
        {% include 'staff/header.html' %}
        {% include 'staff/navigation.html' %}

        <section id="table__sec">
            <article id="table__one">
                <header id="top__table__imgs">
                    <div id="top__table__imgs_cont">
                        {%for img in object.product_images.all %}
                        {% if img %}
                        <details class="top__table__img">
                            <summary>
                                <img src="{{img.file.url}}" alt="" class="hm_main_body_art_img">
                            </summary>
                            <p>
                                <div class="table__ctrl__btns">
                                    <a href="{% url 'store:update_product_image' img.id %}" class="tbl__btn__edit__b"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'store:delete_product_img' img.id %}" class="tbl__btn__delete__b"><i class="fas fa-trash"></i></a>
                                </div>
                            <p>
                        </details>
                        {%else%}
                        {%endif%}
                        {%endfor%}
                    </div>
                </header>
                <section id="top__table__body">
                    <table>
                        <tbody id="table__one__body">
                            <tr>
                                <th>Name</th>
                                <th>{{object.name}}</th>
                                <th>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_name' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </th>
                            </tr>
                            <tr>
                                <td>Category </td>
                                <td>{{object.category}}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_cat' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Brand </td>
                                <td>{{object.brand}}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_brand' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>colors</td>
                                <td>{{object.colors}}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_colors' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>sizes</td>
                                <td>{{object.sizes}}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_sizes' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Price</td>
                                <td>&#8358; {{object.price}}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_price' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Discount price</td>
                                <td>{% if object.discount_price %}&#8358; {{object.discount_price}}{%else%} - {%endif%}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_discount_price' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Product description</td>
                                <td>{{object.description}}</td>
                                <td>
                                    <div class="table__ctrl__btns2">
                                        <a href="{% url 'store:update_product_description' object.product_id %}" class="tbl__btn__edit"><i class="far fa-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </section>
            </article>
        </section>
    </main>
{% endblock %}

main_store/templates/staff/product_images.html
{% extends 'staff/main.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <main id="gall__main__main">
        {% include 'staff/header.html' %}
        {% include 'staff/navigation.html' %}
        <section id="gall__main">

            <article class=" gall__art__one__main ">
                <header><span class="gall_art_sec_name">{{p.name}}</span>
                    <span class="gall_art_item_add_btn">
                        <a href="{% url 'store:add_product_img'%}" class="add_item_btn"><i class="fas fa-plus "></i> images</a>
                    </span>
                </header>
                {% if product_images %}
                {%for p in products%}
                <section class="gall__arts " id="gall__art__one ">
                    {%for img in product_images %}
                    {% if img.product.name == p.name %}
                    <div class="gall__art__img__div ">
                        <img src="{{img.file.url}}" alt="photo image" class="gall__art__one__img">
                        <div class="gall__art__one__img__desc">
                            <a href="{% url 'store:update_product_image' img.id %}" class="gall__art__img__one__name tbl__btn__edit"><i class="far fa-edit"></i></a>
                            <section class="gall__art__img__one__num "><a href="{% url 'store:delete_product_img' img.id %}" class="tbl__btn__delete ">
                                <i class="fas fa-trash "></i></a>
                            </section>
                        </div>
                    </div>
                    {%else%}
                    {%endif%}
                    {%endfor%}
                </section>
                {%endfor%}
                {%else%}
                {%endif%}
            </article>
        </section>
    </main>
{% endblock %}